services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=blackhole-back-someUUID'
      - 'POSTGRES_PASSWORD=random'
      - 'POSTGRES_USER=ONEDAY'
    ports:
      - "5432:5432"
