spring.application.name=backend

spring.datasource.url=jdbc\:postgresql\://localhost\:5432/blackhole-back-someUUID
spring.datasource.username=ONEDAY
spring.datasource.password=random

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.data.web.pageable.serialization-mode=via-dto

blackhole.repodata.path=/path/to/repodata
blackhole.repodata.files.x86_64=x86_64-repodata
blackhole.repodata.files.aarch64=aarch64-repodata
blackhole.repodata.files.x86_64-musl=x86_64-musl-repodata
blackhole.repodata.files.aarch64-musl=aarch64-musl-repodata
