spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=validate

spring.data.web.pageable.serialization-mode=via-dto
spring.data.web.pageable.max-page-size=25
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.page-parameter=pageNumber
spring.data.web.pageable.size-parameter=pageSize

blackhole.repodata.path=${BLACKHOLE_REPODATA_PATH}
blackhole.repodata.files.x86_64=x86_64-repodata
blackhole.repodata.files.aarch64=aarch64-repodata
blackhole.repodata.files.x86_64-musl=x86_64-musl-repodata
blackhole.repodata.files.aarch64-musl=aarch64-musl-repodata
